name: capar
version: 3.0.0+21
publish_to: none
description: Capar of Turkmenpost.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  awesome_notifications: ^0.6.21
  badges: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.6.3
  firebase_messaging: ^12.0.1
  flex_color_scheme: ^5.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.5
  flutter_screenutil: ^5.3.0
  flutter_secure_storage: ^5.0.2
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.2
  flutter_typeahead: ^4.0.0
  get: ^4.5.1
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  lottie: ^1.2.2
  mask_text_input_formatter: ^2.0.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  upgrader: ^4.5.0
  url_launcher: ^6.0.17
  provider: ^6.0.3
  flutter_localizations:
    sdk: flutter
  retrofit: ^3.0.1+1
  json_annotation: ^4.5.0
  build_config: ^1.0.0
  built_value_generator: ^8.3.2
  build_runner: ^2.1.11
  webview_flutter: ^3.0.4
  # new_version: ^0.3.1
#  contact_picker: ^0.0.2
#  permission_handler: ^10.0.0
  contacts_service: ^0.6.3
  # fast_contacts: ^1.1.1
  permission_handler: ^10.0.0
  auto_size_text: ^3.0.0
  toggle_switch: ^2.0.1
  sqflite: ^2.0.3+1
  
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  grpc: ^3.0.2
  protobuf: ^2.1.0
# flutter_native_splash:
#   background_image: "assets/images/splash.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/newSVG/
    - assets/images/chat.svg
    - assets/images/login.svg
    - assets/images/signup.svg
    # - assets/images/onBoarding/first.png
    # - assets/images/onBoarding/second.png
    # - assets/images/onBoarding/thrid.png
    # - assets/images/registration/main_top.png
    # - assets/images/registration/login_bottom.png
    # - assets/images/registration/main_bottom.png
    # - assets/images/registration/signup_top.png
    # - assets/app_icon.png
    # - assets/images/about_home_ic.png
    # - assets/icons/home_menu_drawer.png
    # - assets/images/cabinet_ic.png
    # - assets/home_page/curier.png
    # - assets/home_page/suw_ic.png
    # - assets/home_page/elekticestwa.png
    # - assets/home_page/agts_ip.png
    # - assets/home_page/agts_ic.png
    # - assets/home_page/agts_net_ic.png
    # - assets/home_page/telcom_net.png
    # - assets/home_page/tmcell_toleg.png
    # - assets/home_page/gai_ic.png
    # - assets/icons/about_us.svg
    # - assets/icons/contact.svg
    # - assets/icons/percent.svg
    # - assets/icons/home.svg
    # - assets/images/splash_logo_2.png
    - assets/images/cards/mock.png
    - assets/images/cards/halkbank.png
    - assets/images/cards/milli.png
    - assets/images/cards/turkmenbasy.png
    - assets/images/cards/dayhan.png
    - assets/images/cards/turkmenistan.png
    - assets/images/cards/senagat.png
    - assets/images/cards/turkmenTurk.png
    - assets/images/cards/rysgal.png
    - assets/images/qrcode.png
    - assets/images/pay/pygg_car.png
    - assets/images/pay/agtsHome.png
    - assets/images/pay/certificat.png
    - assets/images/pay/utils.png
    - assets/images/pay/el.png
    - assets/images/pay/iptv.png
    - assets/images/pay/students.png
    - assets/images/pay/tmcell.png
    - assets/images/pay/tv.png
    - assets/images/pay/water.png
    - assets/images/pay/wifi-agts.png
    - assets/images/pay/wifi-telecom.png
    - assets/images/pay/migration.png
    - assets/images/saveReceipt.png
    - assets/images/postReciept.png
    - assets/images/del3.json
    - assets/images/newSVG/error.svg
    - assets/images/newSVG/success.svg
    - assets/images/newSVG/info.svg
    # - assets/images/pay/agtd_logo.png
    # - assets/images/pay/telekom_logo.png
    # - assets/images/pay/tmcell_logo.png
    # - assets/images/newSVG/moto_courier.png
    - assets/images/newSVG/pyggBaner.png
    - assets/images/newSVG/cars.svg
    # - assets/images/newSVG/electroity.svg
    - assets/images/newSVG/licenses.svg
    - assets/images/newSVG/net.svg
    - assets/images/newSVG/utils.svg
    - assets/images/newSVG/phone.svg
    - assets/images/newSVG/phone_smart.svg
    - assets/images/newSVG/student.svg
    - assets/images/newSVG/tv.svg
    - assets/images/newSVG/water.svg
    - assets/images/newSVG/wifi.svg
    - assets/images/newSVG/about.svg
    - assets/images/newSVG/edit.svg
    - assets/images/newSVG/personCabinet.svg
    - assets/images/newSVG/plus.svg
    - assets/images/newSVG/amount.svg
    - assets/images/newSVG/box.svg
    - assets/images/newSVG/car.svg
    # - assets/images/newSVG/cards.svg
    - assets/images/newSVG/contacts.svg
    - assets/images/newSVG/courier.svg
    - assets/images/newSVG/departments.svg
    - assets/images/newSVG/fine.svg
    - assets/images/newSVG/home.svg
    - assets/images/newSVG/languages.svg
    - assets/images/newSVG/loading.svg
    - assets/images/newSVG/location.svg
    - assets/images/newSVG/moto_courier.svg
    - assets/images/newSVG/namesurname.svg
    - assets/images/newSVG/old_phone.svg
    - assets/images/newSVG/payments.svg
    - assets/images/newSVG/person.svg
    - assets/images/newSVG/police.svg
    - assets/images/newSVG/search.svg
    - assets/images/newSVG/star.svg
    - assets/images/newSVG/telephone.svg
    - assets/images/newSVG/menu.svg
    - assets/images/newSVG/rate.svg
    - assets/images/pay/certificat.png

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arialbd.ttf
          weight: 900
        - asset: assets/fonts/arial.ttf
          weight: 700
        - asset: assets/fonts/arial.ttf
flutter_intl:
  enabled: true